# Generated by Django 4.0.5 on 2022-06-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('Tank', 'Танки'), ('DD', 'ДД'), ('Heal', 'Хилы'), ('Gildemaster', 'Гилдмастеры'), ('Spellmaster', 'Мыстера заклинаний'), ('Buyers', 'Торговцы'), ('Quest', 'Кыестгиверы'), ('Smith', 'Кузнецы'), ('Tanner', 'Кодевники'), ('potion', 'Зельевары')], default='DD', max_length=11)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('text', models.TextField(verbose_name='Содержимое отклика')),
                ('accept_status', models.BooleanField(default=False, verbose_name='Принятие отклика')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post', verbose_name='Пост отклика')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
